# GoLangCI-Lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  # timeout for analysis
  timeout: 5m
  # If set we pass it to "go list -mod={option}". From "go help list":
  # -mod=mod make the go command ignore the go.mod file and go.sum file, and instead use the latest versions of all dependencies.
  # -mod=readonly makes the go command treat the go.mod file as read-only.
  modules-download-mode: readonly
  go: '1.26'

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions|teamcity
  # default is "colored-line-number"
  formats:
    - format: colored-line-number

linters:
  # Disable all linters by default
  disable-all: true
  enable:
    # basic linters
    - errcheck          # Errcheck is a program for checking for unchecked errors in go programs
    - gosimple          # Linter for Go source code that specializes on simplifying code
    - govet             # Vet examines Go source code and reports suspicious constructs
    - ineffassign       # Detects when assignments to existing variables are not being used
    - staticcheck       # It's a set of rules from staticcheck. It's not the same thing as the staticcheck binary
    - typecheck         # Like the front-end of a Go compiler, parses and type-checks Go code
    - unused            # Checks Go code for unused constants, variables, functions and types

    # comment linters
    - godot             # Check if comments end with a period
    - revive            # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint

    # naming linters
    - varnamelen        # Checks that shadow variables do not contain any unnecessary type declarations

    # format linters
    - gofmt             # Gofmt checks whether code was gofmt-ed
    - goimports         # In addition to fixing imports, goimports also formats your code in the same style as gofmt
    - wsl               # Whitespace Linter

    # style linters
    - misspell          # Misspell is a linter that finds commonly misspelled English words in comments
    - stylecheck        # Stylecheck is a replacement for golint
    - unconvert         # Remove unnecessary type conversions

    # error linters
    - errorlint         # errorlint is a linter for finding code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - err113            # Finds the code that will cause problems with the error wrapping scheme introduced in Go 1.13

    # performance linters
    - prealloc          # Finds slice declarations that could potentially be pre-allocated

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - stylecheck
    # Exclude godot in tests
    - path: _test\.go
      text: "Comment should end in a period"
      linters:
        - godot

severity:
  # Set the default severity for issues without explicit severity in their configuration
  default-severity: warning
  rules:
    - linters:
        - revive
      text: "exported"
      severity: warning
linters-settings:
  goimports:
    local-prefixes: api
  godot:
    # check all top-level comments, not just exported ones
    scope: all
    # list of regexps for excluding particular comment lines from check
    exclude:
      # Exclude comments that contain 'Example'
      - '^\s*\/\/\s*Example'
      - '^\s*\/\/\s*nolint'
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
        arguments: [ "checkPrivateReceivers" ]
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: unexported-naming
      - name: unreachable-code
      - name: unused-parameter
      - name: var-declaration
      - name: var-naming
      - name: unconditional-recursion
  stylecheck:
    # This option allows you to configure the maximum number of blank lines allowed within a function.
    max-blank-lines: 2

